var wms_layers = [];


        var lyr_YandexSatellite_0 = new ol.layer.Tile({
            'title': 'Yandex Satellite',
            'opacity': 1.000000,
            
            
            source: new ol.source.XYZ({
            attributions: ' ',
                url: 'https://sat04.maps.yandex.net/tiles?l=sat&x={x}&y={y}&z={z}'
            })
        });

        var lyr_OSMStandard_1 = new ol.layer.Tile({
            'title': 'OSM Standard',
            'opacity': 1.000000,
            
            
            source: new ol.source.XYZ({
            attributions: ' &middot; <a href="https://www.openstreetmap.org/copyright">© OpenStreetMap contributors, CC-BY-SA</a>',
                url: 'http://tile.openstreetmap.org/{z}/{x}/{y}.png'
            })
        });
var format_highway_2 = new ol.format.GeoJSON();
var features_highway_2 = format_highway_2.readFeatures(json_highway_2, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_highway_2 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_highway_2.addFeatures(features_highway_2);
var lyr_highway_2 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_highway_2, 
                style: style_highway_2,
                popuplayertitle: "highway",
                interactive: true,
                title: '<img src="styles/legend/highway_2.png" /> highway'
            });
var format_building_3 = new ol.format.GeoJSON();
var features_building_3 = format_building_3.readFeatures(json_building_3, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_building_3 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_building_3.addFeatures(features_building_3);
var lyr_building_3 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_building_3, 
                style: style_building_3,
                popuplayertitle: "building",
                interactive: true,
                title: '<img src="styles/legend/building_3.png" /> building'
            });

lyr_YandexSatellite_0.setVisible(true);lyr_OSMStandard_1.setVisible(true);lyr_highway_2.setVisible(true);lyr_building_3.setVisible(true);
var layersList = [lyr_YandexSatellite_0,lyr_OSMStandard_1,lyr_highway_2,lyr_building_3];
lyr_highway_2.set('fieldAliases', {'fid': 'fid', 'full_id': 'full_id', 'osm_id': 'osm_id', 'osm_type': 'osm_type', 'highway': 'highway', 'flood_prone': 'flood_prone', 'tracktype': 'tracktype', 'kerb': 'kerb', 'width': 'width', 'noname': 'noname', 'motor_vehicle': 'motor_vehicle', 'wheelchair': 'wheelchair', 'trail_visibility': 'trail_visibility', 'snowmobile': 'snowmobile', 'ski': 'ski', 'sac_scale': 'sac_scale', 'horse': 'horse', 'smoothness': 'smoothness', 'crossing:markings': 'crossing:markings', 'intermittent': 'intermittent', 'ford': 'ford', 'access': 'access', 'covered': 'covered', 'incline': 'incline', 'was:highway': 'was:highway', 'traffic_calming': 'traffic_calming', 'description': 'description', 'crossing': 'crossing', 'tunnel': 'tunnel', 'segregated': 'segregated', 'layer': 'layer', 'bridge': 'bridge', 'addr:suburb': 'addr:suburb', 'junction': 'junction', 'ref': 'ref', 'cutting': 'cutting', 'living_street': 'living_street', 'service': 'service', 'foot': 'foot', 'oneway': 'oneway', 'name:ru': 'name:ru', 'name:en': 'name:en', 'name:etymology:wikidata': 'name:etymology:wikidata', 'lit': 'lit', 'maxspeed': 'maxspeed', 'lanes': 'lanes', 'surface': 'surface', 'sidewalk': 'sidewalk', 'name': 'name', 'footway': 'footway', 'bicycle': 'bicycle', });
lyr_building_3.set('fieldAliases', {'fid': 'fid', 'full_id': 'full_id', 'osm_id': 'osm_id', 'osm_type': 'osm_type', 'building': 'building', 'craft': 'craft', 'start_date': 'start_date', 'roof:shape': 'roof:shape', 'energy_class': 'energy_class', 'building:flats': 'building:flats', 'addr:province': 'addr:province', 'payment:debit_cards': 'payment:debit_cards', 'payment:credit_cards': 'payment:credit_cards', 'railway': 'railway', 'contact:website': 'contact:website', 'contact:phone': 'contact:phone', 'contact:email': 'contact:email', 'capacity': 'capacity', 'rating': 'rating', 'fax': 'fax', 'fee': 'fee', 'attraction': 'attraction', 'recycling_type': 'recycling_type', 'recycling:plastic_bags': 'recycling:plastic_bags', 'recycling:glass_bottles': 'recycling:glass_bottles', 'generator:source': 'generator:source', 'generator:method': 'generator:method', 'license_classes': 'license_classes', 'denomination': 'denomination', 'brand': 'brand', 'height': 'height', 'fuel:octane_95': 'fuel:octane_95', 'fuel:octane_92': 'fuel:octane_92', 'tower:type': 'tower:type', 'payment:notes': 'payment:notes', 'building:facade:material': 'building:facade:material', 'rooms': 'rooms', 'resort': 'resort', 'atm': 'atm', 'addr:region': 'addr:region', 'tourism': 'tourism', 'name:ja': 'name:ja', 'military': 'military', 'building:facade:colour': 'building:facade:colour', 'man_made': 'man_made', 'branch': 'branch', 'tactile_paving': 'tactile_paving', 'covered': 'covered', 'public_transport': 'public_transport', 'bus': 'bus', 'disused': 'disused', 'level': 'level', 'layer': 'layer', 'name:ru': 'name:ru', 'name:en': 'name:en', 'ruins': 'ruins', 'barrier': 'barrier', 'short_name': 'short_name', 'substation': 'substation', 'healthcare': 'healthcare', 'dispensing': 'dispensing', 'landuse': 'landuse', 'foot': 'foot', 'bicycle': 'bicycle', 'social_facility:for': 'social_facility:for', 'social_facility': 'social_facility', 'office': 'office', 'government': 'government', 'voltage': 'voltage', 'ref': 'ref', 'power': 'power', 'location': 'location', 'access': 'access', 'building:facade:color': 'building:facade:color', 'operator': 'operator', 'old_name': 'old_name', 'abandoned': 'abandoned', 'sport': 'sport', 'leisure': 'leisure', 'training': 'training', 'description': 'description', 'internet_access': 'internet_access', 'club': 'club', 'payment:visa': 'payment:visa', 'payment:mastercard': 'payment:mastercard', 'payment:cash': 'payment:cash', 'religion': 'religion', 'shop': 'shop', 'opening_hours': 'opening_hours', 'amenity': 'amenity', 'addr:postcode': 'addr:postcode', 'alt_name': 'alt_name', 'official_name': 'official_name', 'wheelchair': 'wheelchair', 'website': 'website', 'type': 'type', 'phone': 'phone', 'name': 'name', 'email': 'email', 'building:levels': 'building:levels', 'addr:street': 'addr:street', 'addr:housenumber': 'addr:housenumber', 'addr:country': 'addr:country', 'addr:city': 'addr:city', 'address': 'address', });
lyr_highway_2.set('fieldImages', {'fid': '', 'full_id': 'TextEdit', 'osm_id': 'TextEdit', 'osm_type': 'TextEdit', 'highway': 'TextEdit', 'flood_prone': 'TextEdit', 'tracktype': 'TextEdit', 'kerb': 'TextEdit', 'width': 'TextEdit', 'noname': 'TextEdit', 'motor_vehicle': 'TextEdit', 'wheelchair': 'TextEdit', 'trail_visibility': 'TextEdit', 'snowmobile': 'TextEdit', 'ski': 'TextEdit', 'sac_scale': 'TextEdit', 'horse': 'TextEdit', 'smoothness': 'TextEdit', 'crossing:markings': 'TextEdit', 'intermittent': 'TextEdit', 'ford': 'TextEdit', 'access': 'TextEdit', 'covered': 'TextEdit', 'incline': 'TextEdit', 'was:highway': 'TextEdit', 'traffic_calming': 'TextEdit', 'description': 'TextEdit', 'crossing': 'TextEdit', 'tunnel': 'TextEdit', 'segregated': 'TextEdit', 'layer': 'TextEdit', 'bridge': 'TextEdit', 'addr:suburb': 'TextEdit', 'junction': 'TextEdit', 'ref': 'TextEdit', 'cutting': 'TextEdit', 'living_street': 'TextEdit', 'service': 'TextEdit', 'foot': 'TextEdit', 'oneway': 'TextEdit', 'name:ru': 'TextEdit', 'name:en': 'TextEdit', 'name:etymology:wikidata': 'TextEdit', 'lit': 'TextEdit', 'maxspeed': 'TextEdit', 'lanes': 'TextEdit', 'surface': 'TextEdit', 'sidewalk': 'TextEdit', 'name': 'TextEdit', 'footway': 'TextEdit', 'bicycle': 'TextEdit', });
lyr_building_3.set('fieldImages', {'fid': 'TextEdit', 'full_id': 'TextEdit', 'osm_id': 'TextEdit', 'osm_type': 'TextEdit', 'building': 'TextEdit', 'craft': 'TextEdit', 'start_date': 'TextEdit', 'roof:shape': 'TextEdit', 'energy_class': 'TextEdit', 'building:flats': 'TextEdit', 'addr:province': 'TextEdit', 'payment:debit_cards': 'TextEdit', 'payment:credit_cards': 'TextEdit', 'railway': 'TextEdit', 'contact:website': 'TextEdit', 'contact:phone': 'TextEdit', 'contact:email': 'TextEdit', 'capacity': 'TextEdit', 'rating': 'TextEdit', 'fax': 'TextEdit', 'fee': 'TextEdit', 'attraction': 'TextEdit', 'recycling_type': 'TextEdit', 'recycling:plastic_bags': 'TextEdit', 'recycling:glass_bottles': 'TextEdit', 'generator:source': 'TextEdit', 'generator:method': 'TextEdit', 'license_classes': 'TextEdit', 'denomination': 'TextEdit', 'brand': 'TextEdit', 'height': 'TextEdit', 'fuel:octane_95': 'TextEdit', 'fuel:octane_92': 'TextEdit', 'tower:type': 'TextEdit', 'payment:notes': 'TextEdit', 'building:facade:material': 'TextEdit', 'rooms': 'TextEdit', 'resort': 'TextEdit', 'atm': 'TextEdit', 'addr:region': 'TextEdit', 'tourism': 'TextEdit', 'name:ja': 'TextEdit', 'military': 'TextEdit', 'building:facade:colour': 'TextEdit', 'man_made': 'TextEdit', 'branch': 'TextEdit', 'tactile_paving': 'TextEdit', 'covered': 'TextEdit', 'public_transport': 'TextEdit', 'bus': 'TextEdit', 'disused': 'TextEdit', 'level': 'TextEdit', 'layer': 'TextEdit', 'name:ru': 'TextEdit', 'name:en': 'TextEdit', 'ruins': 'TextEdit', 'barrier': 'TextEdit', 'short_name': 'TextEdit', 'substation': 'TextEdit', 'healthcare': 'TextEdit', 'dispensing': 'TextEdit', 'landuse': 'TextEdit', 'foot': 'TextEdit', 'bicycle': 'TextEdit', 'social_facility:for': 'TextEdit', 'social_facility': 'TextEdit', 'office': 'TextEdit', 'government': 'TextEdit', 'voltage': 'TextEdit', 'ref': 'TextEdit', 'power': 'TextEdit', 'location': 'TextEdit', 'access': 'TextEdit', 'building:facade:color': 'TextEdit', 'operator': 'TextEdit', 'old_name': 'TextEdit', 'abandoned': 'TextEdit', 'sport': 'TextEdit', 'leisure': 'TextEdit', 'training': 'TextEdit', 'description': 'TextEdit', 'internet_access': 'TextEdit', 'club': 'TextEdit', 'payment:visa': 'TextEdit', 'payment:mastercard': 'TextEdit', 'payment:cash': 'TextEdit', 'religion': 'TextEdit', 'shop': 'TextEdit', 'opening_hours': 'TextEdit', 'amenity': 'TextEdit', 'addr:postcode': 'TextEdit', 'alt_name': 'TextEdit', 'official_name': 'TextEdit', 'wheelchair': 'TextEdit', 'website': 'TextEdit', 'type': 'TextEdit', 'phone': 'TextEdit', 'name': 'TextEdit', 'email': 'TextEdit', 'building:levels': 'TextEdit', 'addr:street': 'TextEdit', 'addr:housenumber': 'TextEdit', 'addr:country': 'TextEdit', 'addr:city': 'TextEdit', 'address': '', });
lyr_highway_2.set('fieldLabels', {'fid': 'no label', 'full_id': 'no label', 'osm_id': 'no label', 'osm_type': 'no label', 'highway': 'no label', 'flood_prone': 'no label', 'tracktype': 'no label', 'kerb': 'no label', 'width': 'no label', 'noname': 'no label', 'motor_vehicle': 'no label', 'wheelchair': 'no label', 'trail_visibility': 'no label', 'snowmobile': 'no label', 'ski': 'no label', 'sac_scale': 'no label', 'horse': 'no label', 'smoothness': 'no label', 'crossing:markings': 'no label', 'intermittent': 'no label', 'ford': 'no label', 'access': 'no label', 'covered': 'no label', 'incline': 'no label', 'was:highway': 'no label', 'traffic_calming': 'no label', 'description': 'no label', 'crossing': 'no label', 'tunnel': 'no label', 'segregated': 'no label', 'layer': 'no label', 'bridge': 'no label', 'addr:suburb': 'no label', 'junction': 'no label', 'ref': 'no label', 'cutting': 'no label', 'living_street': 'no label', 'service': 'no label', 'foot': 'no label', 'oneway': 'no label', 'name:ru': 'no label', 'name:en': 'no label', 'name:etymology:wikidata': 'no label', 'lit': 'no label', 'maxspeed': 'no label', 'lanes': 'no label', 'surface': 'no label', 'sidewalk': 'no label', 'name': 'no label', 'footway': 'no label', 'bicycle': 'no label', });
lyr_building_3.set('fieldLabels', {'fid': 'no label', 'full_id': 'no label', 'osm_id': 'no label', 'osm_type': 'no label', 'building': 'no label', 'craft': 'no label', 'start_date': 'no label', 'roof:shape': 'no label', 'energy_class': 'no label', 'building:flats': 'no label', 'addr:province': 'no label', 'payment:debit_cards': 'no label', 'payment:credit_cards': 'no label', 'railway': 'no label', 'contact:website': 'no label', 'contact:phone': 'no label', 'contact:email': 'no label', 'capacity': 'no label', 'rating': 'no label', 'fax': 'no label', 'fee': 'no label', 'attraction': 'no label', 'recycling_type': 'no label', 'recycling:plastic_bags': 'no label', 'recycling:glass_bottles': 'no label', 'generator:source': 'no label', 'generator:method': 'no label', 'license_classes': 'no label', 'denomination': 'no label', 'brand': 'no label', 'height': 'no label', 'fuel:octane_95': 'no label', 'fuel:octane_92': 'no label', 'tower:type': 'no label', 'payment:notes': 'no label', 'building:facade:material': 'no label', 'rooms': 'no label', 'resort': 'no label', 'atm': 'no label', 'addr:region': 'no label', 'tourism': 'no label', 'name:ja': 'no label', 'military': 'no label', 'building:facade:colour': 'no label', 'man_made': 'no label', 'branch': 'no label', 'tactile_paving': 'no label', 'covered': 'no label', 'public_transport': 'no label', 'bus': 'no label', 'disused': 'no label', 'level': 'no label', 'layer': 'no label', 'name:ru': 'no label', 'name:en': 'no label', 'ruins': 'no label', 'barrier': 'no label', 'short_name': 'no label', 'substation': 'no label', 'healthcare': 'no label', 'dispensing': 'no label', 'landuse': 'no label', 'foot': 'no label', 'bicycle': 'no label', 'social_facility:for': 'no label', 'social_facility': 'no label', 'office': 'no label', 'government': 'no label', 'voltage': 'no label', 'ref': 'no label', 'power': 'no label', 'location': 'no label', 'access': 'no label', 'building:facade:color': 'no label', 'operator': 'no label', 'old_name': 'no label', 'abandoned': 'no label', 'sport': 'no label', 'leisure': 'no label', 'training': 'no label', 'description': 'no label', 'internet_access': 'no label', 'club': 'no label', 'payment:visa': 'no label', 'payment:mastercard': 'no label', 'payment:cash': 'no label', 'religion': 'no label', 'shop': 'no label', 'opening_hours': 'no label', 'amenity': 'no label', 'addr:postcode': 'no label', 'alt_name': 'no label', 'official_name': 'no label', 'wheelchair': 'no label', 'website': 'no label', 'type': 'no label', 'phone': 'no label', 'name': 'no label', 'email': 'no label', 'building:levels': 'no label', 'addr:street': 'no label', 'addr:housenumber': 'no label', 'addr:country': 'no label', 'addr:city': 'no label', 'address': 'no label', });
lyr_building_3.on('precompose', function(evt) {
    evt.context.globalCompositeOperation = 'normal';
});